// Temporary data for testing purposes
const data = [
  // i: task.id, x: date mapped to weekDay index, y: time mapped to hour index, w: 1, h: task.size
  { i: "a", x: 0, y: 0, w: 1, h: 1, title: "Take car to MOT" },
  { i: "b", x: 0, y: 1, w: 1, h: 1, title: "Hoover" },
  {
    i: "c",
    x: 0,
    y: 8,
    w: 1,
    h: 6,
    title: "Meeting with Sam",
    description: "Lorem ipsum dolor sit amet consecteteur adipiscing elit",
  },
  {
    i: "d",
    x: 0,
    y: 18,
    w: 1,
    h: 4,
    title: "Run",
    description: "2mi WU, 4mi tempo, 2mi CD",
  },
  {
    i: "e",
    x: 1,
    y: 3,
    w: 1,
    h: 6,
    title: "Doctor's appointment",
    description: "Parking available on Rouen Road",
    completed: true,
  },
  { i: "f", x: 1, y: 9, w: 1, h: 1, title: "Lunch with Pete" },
  {
    i: "g",
    x: 1,
    y: 11,
    w: 1,
    h: 5,
    title: "Work on app",
    description: "Complete design V2",
    completed: true,
  },
  { i: "h", x: 2, y: 1, w: 1, h: 1, title: "Take out bins" },
  {
    i: "i",
    x: 2,
    y: 12,
    w: 1,
    h: 6,
    title: "Michael's funeral",
    description: "Ellough Crematorium",
  },
  {
    i: "j",
    x: 2,
    y: 18,
    w: 1,
    h: 6,
    title: "Wake at the Angel",
    description: "Angel, Halesworth. Consider transport?",
  },
  {
    i: "l",
    x: 4,
    y: 6,
    w: 1,
    h: 2,
    title: "Run",
    description: "5K easy",
  },
  {
    i: "m",
    x: 4,
    y: 20,
    w: 1,
    h: 6,
    title: "Band practice",
    description: "Plug Studios, 6pm-9pm",
  },
  {
    i: "n",
    x: 5,
    y: 6,
    w: 1,
    h: 2,
    title: "Run",
    description: "5K easy",
  },
  {
    i: "o",
    x: 5,
    y: 8,
    w: 1,
    h: 12,
    title: "Pub crawl",
    description: "Dinner at Haggle at 6pm",
  },
];

export { data };
